on:
  workflow_call:
    inputs:
      working-directory:
        description: "Directory to release from"
        default: "./"
        required: false
        type: string
    secrets:
      GH_READ_PACKAGES_TOKEN:
        required: true

permissions:
  contents: write
  packages: write
  issues: write
env: # <--- here
  NEXT_PUBLIC_FIREBASE_TOKEN: ${{ secrets.NEXT_PUBLIC_FIREBASE_TOKEN }} #
jobs:
  npm-release:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
          registry-url: "https://npm.pkg.github.com"
          scope: "@bx-looop"
      - name: Install dependencies
        run: yarn install
        env:
          NODE_AUTH_TOKEN: ${{secrets.GH_READ_PACKAGES_TOKEN}}
      - name: add env variables
        run: |
          touch .env.local
          echo NEXT_PUBLIC_MAPS_API_KEY=${{ secrets.NEXT_PUBLIC_MAPS_API_KEY }} >> .env
          echo MAPS_API_KEY=${{ secrets.NEXT_PUBLIC_MAPS_API_KEY }} >> .env
          echo NEXT_PUBLIC_GOOGLE_ANALYTICS=${{ secrets.NEXT_PUBLIC_GOOGLE_ANALYTICS }} >> .env
          echo NEXT_PUBLIC_TAG_MANAGER_GTMID=${{ secrets.NEXT_PUBLIC_TAG_MANAGER_GTMID }} >> .env
          echo NEXT_PUBLIC_HOTJAR_SITE_ID=${{ secrets.NEXT_PUBLIC_HOTJAR_SITE_ID }} >> .env
          echo NEXT_PUBLIC_HOTJAR_SITE_HJSV=${{ secrets.NEXT_PUBLIC_HOTJAR_SITE_HJSV }} >> .env
          cat .env.local

      - name: Run Build
        run: yarn build
        working-directory: ${{ inputs.working-directory }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_READ_PACKAGES_TOKEN }}

      # Release npm package
      - name: Release
        run: npx semantic-release
        working-directory: ${{ inputs.working-directory }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
