on:
  workflow_call:
    inputs:
      working-directory:
        description: "Directory to release from"
        default: "./"
        required: false
        type: string
    secrets:
      GH_READ_PACKAGES_TOKEN:
        required: true

permissions:
  contents: write
  packages: write
  issues: write

jobs:
  npm-release:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
          registry-url: "https://npm.pkg.github.com"
          scope: "@bx-looop"

      - name: Install dependencies
        run: npm ci
        working-directory: ${{ inputs.working-directory }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_READ_PACKAGES_TOKEN }}

      - name: Run Build
        run: npm run build
        working-directory: ${{ inputs.working-directory }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_READ_PACKAGES_TOKEN }}

      # Release npm package
      - name: Release
        run: npx semantic-release
        working-directory: ${{ inputs.working-directory }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
