name: SonarQube Analyze

on:
  workflow_call:
    inputs:
      coverage-command:
        required: true
        type: string
      coverage-path:
        required: false
        default: "./coverage/lcov.info"
        type: string
    secrets:
      NPM_GRANULAR_TOKEN:
        required: true
      SONAR_TOKEN:
        required: true
      SONAR_HOST_URL:
        required: true

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history to get the full coverage report

      - name: Set up Node.js v22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: "https://registry.npmjs.org"
          scope: "@bxtech"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile --immutable
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_GRANULAR_TOKEN }}

      - name: Run tests and generate coverage
        run: ${{ inputs.coverage-command }}
        env:
          NODE_OPTIONS: --max-old-space-size=4096

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          NODE_OPTIONS: --max-old-space-size=4096
        with:
          args: >
            -Dsonar.javascript.lcov.reportPaths=${{ inputs.coverage-path }}
            -Dsonar.javascript.node.maxspace=4096
